### PR TITLE
Update network.md

### PR DESCRIPTION
**Pull request by scummboy**
Added documentation on how to add a MiSTer to a Tailnet and have tailscale start on boot.

### CODE REVIEW

**Comment by birdybro** [comment]
Looks good, thanks!

**Comment by multi-vitamin** [comment]
Has anyone had success with tailscale?
I've tried several packages and they all fail with different messages.

**Comment by birdybro** [comment]
@scummboy does the firewall_on script need to be ran to make this work?

**Comment by scummboy** [comment]
I did not run it on my MiSTer, but since it was a MiSTer Pi it might be that the offline install pre-set firewall_on.sh for me.

**Pull request merged**
