### PR TITLE
Update computer.md

### PR DESCRIPTION
**Pull request by thera34**
Hello, I would propose this modification on C64 section, to reflect the changes done in C64 core. 
For UP9600 mode, I still need to do some tests, and come back at a later point

### CODE REVIEW

**Comment by sorgelig** [comment]
UP9600 is implemented and tested. I've forgot which terminal app i've used however..

**Comment by birdybro** [comment]
@thera34 Whenever you figure out UP9600, feel free to submit another PR :)

Thank you!

**Comment by thera34** [comment]
Just did, found out the terminal which works :)

**Comment by birdybro** [comment]
> UP9600 is implemented and tested. I've forgot which terminal app i've used however..

Thanks for the suggestion @sorgelig, @thera34 just added that documentation too. :)

**Pull request merged**
