### PR TITLE
Update computer.md

### PR DESCRIPTION
**Pull request by thera34**
Added CoCo3 mini how-to for connecting to BBSes using Ultimaterm

### CODE REVIEW

**Comment by birdybro** [comment]
Thank you! Looks good! :)

**Comment by birdybro** [comment]
I changed the formatting to fit with the other pages a bit. Can you do me a favor and review the modifications I made at the end to make sure I got the syntax correct? If not can you adjust it for me, or let me know how it should be?

https://github.com/MiSTer-devel/MkDocs_MiSTer/blob/8e22dca7fb0a30ec34c1d8af9a9e6f09d6930dba/docs/advanced/computer.md?plain=1#L87

https://github.com/MiSTer-devel/MkDocs_MiSTer/blob/8e22dca7fb0a30ec34c1d8af9a9e6f09d6930dba/docs/advanced/computer.md?plain=1#L91

Thanks again!

**Comment by thera34** [comment]
Hello, 
The load command for CoCo3 should be LOADM"ULTIMATE , without the last quotation mark ("). Other than that looks fine.
I will modify it after work, along with the rest of the page to have the key shortcuts like you did. Also I will re-work a bit on serial/ppp connections on DOS/WIN/OS2 for 486.

Have a nice day ahead !

**Comment by birdybro** [comment]
Very cool, thank you!

**Pull request merged**
